### ISSUE TITLE
failed to open 3D models if download zipped file and cloning repository gives problem of LFS bandwidth

### ISSUE THREAD

**Issue by imranmu** [IKEA/IKEA3DAssemblyDataset#4]
###  There are two issues
- One is related to downloading the entire repo as a zipped folder. The 3D models failed to open.
- Second is cloning the repository. The bug repost is attached.

> Downloading Dataset/BEKVÄM_30178884/glTF_glb/BEKVÄM_30178884.glb (43 MB)
> Error downloading object: Dataset/BEKVÄM_30178884/glTF_glb/BEKVÄM_30178884.glb (ac5880e): Smudge error: Error downloading Dataset/BEKVÄM_30178884/glTF_glb/BEKVÄM_30178884.glb (ac5880e19397d8389cd49dbc742cf7b0aa5d5a1b8c25de7c4cbb879749b51891): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by TnyPny** [comment]
@imranmu Thank you for reporting!

1. It's not possible to download the dataset using .zipped folder since the models are LFS (large file size), and they don't follow along when GitHub creates the .zip files. The repository has to be cloned (but right now that is prevented because of the second issues "bandwidth quota"). Depending on how we solve the "bandwidth quota" issue, I will clarify on the readme.md page on how to successfully download the models.
2. We confirm we have a "bandwidth quota" issue and we are investigating a solution for it.

**Comment by TnyPny** [comment]
@imranmu We added an **IKEA3DAssemblyDataset-v1-0.zip** to the [release note for v.1.0 ](https://github.com/IKEA/IKEA3DAssemblyDataset/releases/tag/v1.0) which contains the 3D models.
This made it possible for us to remove the use of LFS (Large File Storage) and makes it easier to download the dataset directly from the release notes, without needing to clone the repository.

We believe this solves issue #4 and with that, we are closing this ticket.
